
export const Keys = {
    // Function keys
    F1: 'F1',
    F2: 'F2',
    F3: 'F3',
    F4: 'F4',
    F5: 'F5',
    F6: 'F6',
    F7: 'F7',
    F8: 'F8',
    F9: 'F9',
    F10: 'F10',
    F11: 'F11',
    F12: 'F12',
  
    // Digit keys
    Digit0: 'Digit0',
    Digit1: 'Digit1',
    Digit2: 'Digit2',
    Digit3: 'Digit3',
    Digit4: 'Digit4',
    Digit5: 'Digit5',
    Digit6: 'Digit6',
    Digit7: 'Digit7',
    Digit8: 'Digit8',
    Digit9: 'Digit9',
  
    // Alphabet keys
    KeyA: 'KeyA',
    KeyB: 'KeyB',
    KeyC: 'KeyC',
    KeyD: 'KeyD',
    KeyE: 'KeyE',
    KeyF: 'KeyF',
    KeyG: 'KeyG',
    KeyH: 'KeyH',
    KeyI: 'KeyI',
    KeyJ: 'KeyJ',
    KeyK: 'KeyK',
    KeyL: 'KeyL',
    KeyM: 'KeyM',
    KeyN: 'KeyN',
    KeyO: 'KeyO',
    KeyP: 'KeyP',
    KeyQ: 'KeyQ',
    KeyR: 'KeyR',
    KeyS: 'KeyS',
    KeyT: 'KeyT',
    KeyU: 'KeyU',
    KeyV: 'KeyV',
    KeyW: 'KeyW',
    KeyX: 'KeyX',
    KeyY: 'KeyY',
    KeyZ: 'KeyZ',
  
    // Special keys
    Backquote: 'Backquote',
    Minus: 'Minus',
    Equal: 'Equal',
    Backslash: 'Backslash',
    Backspace: 'Backspace',
    Tab: 'Tab',
    Delete: 'Delete',
    Escape: 'Escape',
    ArrowDown: 'ArrowDown',
    ArrowEnd: 'ArrowEnd',
    ArrowHome: 'ArrowHome',
    ArrowLeft: 'ArrowLeft',
    ArrowPageDown: 'ArrowPageDown',
    ArrowPageUp: 'ArrowPageUp',
    ArrowRight: 'ArrowRight',
    ArrowUp: 'ArrowUp',
    Enter: 'Enter',
    Space: 'Space',
    Insert: 'Insert',
  
    // Modifier keys
    Shift: 'Shift',
    Control: 'Control',
    Alt: 'Alt',
    Meta: 'Meta',
    ControlOrMeta: 'ControlOrMeta'
  };
  